-- migrate:up
CREATE TABLE users(
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    kakaoId bigint NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    profileImage  VARCHAR(500) NULL,
    password VARCHAR(200) NOT NULL,
    address VARCHAR(200) NULL,
    point DECIMAL(10,2) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    
-- migrate:down
DROP TABLE users;